// apps/mobile/src/components/ui/password-requirements.tsx
import { PASSWORD_STRONG_REQUIREMENTS } from '@finance/shared';
import { CheckCircleIcon, CircleIcon } from 'phosphor-react-native';
import { View } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { BrandColors } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';

/**
 * Checklist visual dos requisitos da senha `strong` (política única em
 * @finance/shared, mesma usada no schema Zod e na API) — reage a cada tecla
 * digitada. Mesmo componente/conceito do PasswordRequirements do dashboard.
 * Só feedback incremental de UI: quem valida de verdade no submit continua
 * sendo o schema Zod.
 */
export function PasswordRequirements({ password = '' }: { password?: string }) {
  const theme = useTheme();

  return (
    <View className="mt-1.5 gap-1">
      {PASSWORD_STRONG_REQUIREMENTS.map((requirement) => {
        const met = requirement.test(password);
        return (
          <View key={requirement.key} className="flex-row items-center gap-1.5">
            {met ? (
              <CheckCircleIcon
                size={14}
                weight="fill"
                color={BrandColors.success}
              />
            ) : (
              <CircleIcon size={14} color={theme.textSecondary} />
            )}
            <ThemedText
              type="small"
              themeColor="textSecondary"
              style={met ? { color: BrandColors.success } : undefined}
            >
              {requirement.label}
            </ThemedText>
          </View>
        );
      })}
    </View>
  );
}

// apps/dashboard/src/lib/components/ui/password-requirements/password-requirements.svelte
<script lang="ts">
	import { PASSWORD_STRONG_REQUIREMENTS } from '@finance/shared';
	import CheckCircleIcon from 'phosphor-svelte/lib/CheckCircle';
	import CircleIcon from 'phosphor-svelte/lib/Circle';
	import { cn } from '$lib/utils.js';

	/**
	 * Checklist visual dos requisitos da senha `strong` (política única em
	 * @finance/shared, mesma usada no Zod do form e da API) — reage a cada
	 * tecla digitada. É só feedback incremental de UI: quem valida de verdade
	 * no submit continua sendo o schema Zod.
	 */
	let { password = '', id }: { password?: string; id?: string } = $props();

	const metCount = $derived(
		PASSWORD_STRONG_REQUIREMENTS.filter((requirement) => requirement.test(password)).length
	);
</script>

<div {id}>
	<span class="sr-only" aria-live="polite">
		{metCount} de {PASSWORD_STRONG_REQUIREMENTS.length} requisitos da senha atendidos
	</span>
	<ul class="mt-1.5 space-y-1 text-xs">
		{#each PASSWORD_STRONG_REQUIREMENTS as requirement (requirement.key)}
			{@const met = requirement.test(password)}
			<li
				class={cn(
					'flex items-center gap-1.5 transition-colors',
					met ? 'text-emerald-600 dark:text-emerald-400' : 'text-muted-foreground'
				)}
			>
				{#if met}
					<CheckCircleIcon size={14} weight="fill" />
				{:else}
					<CircleIcon size={14} />
				{/if}
				{requirement.label}
			</li>
		{/each}
	</ul>
</div>
