// apps/dashboard/src/routes/(app)/more/transfers/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { resolve } from '$app/paths';

	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';
	import { Select } from '$lib/components/ui/select';
	import { formatCents } from '$lib/money';

	let { data, form } = $props();

	function timeLeft(iso: string): string {
		const days = Math.ceil((new Date(iso).getTime() - Date.now()) / 86_400_000);
		return days <= 0 ? 'expira hoje' : `expira em ${days}d`;
	}

	const transferAccountOptions = $derived(
		data.transferAccounts.map((account) => ({
			value: account.accountId,
			label: `${account.accountName} · ${account.workspaceName}`
		}))
	);

	/** Uma seleção por transferência pendente (cada card tem seu próprio form/select). */
	let pendingAccountSelection = $state<Record<string, string>>({});
</script>

<svelte:head>
	<title>Transferências — Marcelus</title>
</svelte:head>

<div class="flex flex-col gap-6">
	<div class="flex flex-wrap items-center justify-between gap-3">
		<h2 class="text-lg font-semibold">Transferências</h2>
		<Button href={resolve('/transactions')} variant="outline"
			>Nova transferência em Transações</Button
		>
	</div>

	{#if form?.message}
		<p class="text-sm text-destructive">{form.message}</p>
	{/if}

	<div>
		<h3 class="mb-2 text-sm font-medium text-muted-foreground">Pendentes recebidas</h3>
		{#if data.pending.length > 0}
			<div class="flex flex-col gap-3">
				{#each data.pending as transfer (transfer.id)}
					<Card.Root>
						<Card.Content class="flex flex-col gap-3 py-4">
							<div>
								<p class="text-sm font-medium">{transfer.fromUserName}</p>
								<p class="text-sm text-muted-foreground">{transfer.description}</p>
								<p class="text-xs text-muted-foreground">{timeLeft(transfer.expiresAt)}</p>
							</div>
							<p class="text-lg font-semibold">{formatCents(transfer.amount)}</p>
							<form method="POST" action="?/accept" use:enhance class="flex flex-col gap-2">
								<input type="hidden" name="transferId" value={transfer.id} />
								<Select
									name="accountId"
									required
									placeholder="Receber em qual conta?"
									options={transferAccountOptions}
									value={pendingAccountSelection[transfer.id] ?? ''}
									onValueChange={(v) => (pendingAccountSelection[transfer.id] = v)}
								/>
								<label class="flex items-center gap-2 text-sm text-muted-foreground">
									<input type="checkbox" name="markTrusted" value="true" />
									Confiar em quem enviou — próximas entram automático
								</label>
								<div class="flex gap-2">
									<Button
										type="submit"
										formaction="?/reject"
										formnovalidate
										variant="outline"
										class="flex-1"
									>
										Recusar
									</Button>
									<Button type="submit" class="flex-1">Aceitar</Button>
								</div>
							</form>
						</Card.Content>
					</Card.Root>
				{/each}
			</div>
		{:else}
			<Card.Root>
				<Card.Content class="py-6 text-center text-sm text-muted-foreground">
					Nenhuma transferência pendente.
				</Card.Content>
			</Card.Root>
		{/if}
	</div>

	<div>
		<h3 class="mb-2 text-sm font-medium text-muted-foreground">Contatos confiáveis</h3>
		{#if data.trustedContacts.length > 0}
			<div class="flex flex-col gap-2">
				{#each data.trustedContacts as contact (contact.id)}
					<Card.Root>
						<Card.Content class="flex items-center justify-between py-3">
							<span class="text-sm font-medium">{contact.trustedUserName}</span>
							<form method="POST" action="?/removeTrustedContact" use:enhance>
								<input type="hidden" name="id" value={contact.id} />
								<Button type="submit" variant="ghost" size="sm" class="text-destructive">
									Remover
								</Button>
							</form>
						</Card.Content>
					</Card.Root>
				{/each}
			</div>
		{:else}
			<Card.Root>
				<Card.Content class="py-6 text-center text-sm text-muted-foreground">
					Nenhum contato confiável ainda.
				</Card.Content>
			</Card.Root>
		{/if}
	</div>
</div>

// apps/mobile/src/app/(app)/transfers/index.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ArrowLeftIcon } from 'phosphor-react-native';
import { useState } from 'react';
import { ActivityIndicator, Pressable, View } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Screen } from '@/components/ui/screen';
import { Select, type SelectOption } from '@/components/ui/select';
import { formatCents } from '@/lib/money';
import { transferApi, type PendingTransfer } from '@/lib/transfer-api';

function timeLeft(iso: string): string {
  const days = Math.ceil((new Date(iso).getTime() - Date.now()) / 86_400_000);
  return days <= 0 ? 'expira hoje' : `expira em ${days}d`;
}

function PendingTransferCard({
  transfer,
  accountOptions,
}: {
  transfer: PendingTransfer;
  accountOptions: SelectOption[];
}) {
  const [accountId, setAccountId] = useState('');
  const [markTrusted, setMarkTrusted] = useState(false);
  const queryClient = useQueryClient();

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['transfers-pending'] });
    queryClient.invalidateQueries({ queryKey: ['accounts'] });
    queryClient.invalidateQueries({ queryKey: ['summary'] });
  };

  const accept = useMutation({
    mutationFn: () => transferApi.accept(transfer.id, { accountId, markTrusted }),
    onSuccess: invalidate,
  });
  const reject = useMutation({
    mutationFn: () => transferApi.reject(transfer.id),
    onSuccess: invalidate,
  });

  return (
    <Card className="gap-3">
      <View>
        <ThemedText type="smallBold">{transfer.fromUserName}</ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          {transfer.description}
        </ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          {timeLeft(transfer.expiresAt)}
        </ThemedText>
      </View>
      <ThemedText type="subtitle">{formatCents(transfer.amount)}</ThemedText>
      <Select
        placeholder="Receber em qual conta?"
        options={accountOptions}
        value={accountId}
        onValueChange={setAccountId}
      />
      <Pressable onPress={() => setMarkTrusted((v) => !v)} className="flex-row items-center gap-2">
        <Checkbox checked={markTrusted} onCheckedChange={setMarkTrusted} />
        <ThemedText type="small">Confiar em quem enviou — próximas entram automático</ThemedText>
      </Pressable>
      <View className="flex-row gap-2">
        <Button className="flex-1" variant="outline" loading={reject.isPending} onPress={() => reject.mutate()}>
          Recusar
        </Button>
        <Button
          className="flex-1"
          disabled={!accountId}
          loading={accept.isPending}
          onPress={() => accept.mutate()}>
          Aceitar
        </Button>
      </View>
    </Card>
  );
}

export default function PendingTransfersScreen() {
  const { data: pending, isLoading } = useQuery({
    queryKey: ['transfers-pending'],
    queryFn: transferApi.listPending,
  });
  const { data: accounts } = useQuery({
    queryKey: ['transfer-accounts'],
    queryFn: transferApi.listAccounts,
  });

  const accountOptions: SelectOption[] = (accounts ?? []).map((a) => ({
    label: `${a.accountName} · ${a.workspaceName}`,
    value: a.accountId,
  }));

  return (
    <Screen className="gap-6 pb-28">
      <View className="flex-row items-center gap-3">
        <Pressable onPress={() => router.back()} hitSlop={8} className="active:opacity-60">
          <ArrowLeftIcon size={22} />
        </Pressable>
        <ThemedText type="subtitle">Transferências pendentes</ThemedText>
      </View>

      {isLoading ? (
        <ActivityIndicator />
      ) : pending && pending.length > 0 ? (
        <View className="gap-3">
          {pending.map((transfer) => (
            <PendingTransferCard key={transfer.id} transfer={transfer} accountOptions={accountOptions} />
          ))}
        </View>
      ) : (
        <Card className="items-center py-8">
          <ThemedText type="small" themeColor="textSecondary">
            Nenhuma transferência pendente.
          </ThemedText>
        </Card>
      )}
    </Screen>
  );
}
