// apps/mobile/src/app/(app)/splits.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ArrowLeftIcon } from 'phosphor-react-native';
import { useState } from 'react';
import { ActivityIndicator, Pressable, View } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Screen } from '@/components/ui/screen';
import { formatCents } from '@/lib/money';
import { splitApi, type OwedByMeShare, type OwedToMeShare } from '@/lib/split-api';

const STATUS_LABELS: Record<string, string> = {
  pending: 'Pendente',
  paid: 'Pago, aguardando confirmação',
  confirmed: 'Confirmado',
};

function OwedByMeCard({ share }: { share: OwedByMeShare }) {
  const queryClient = useQueryClient();
  const markPaid = useMutation({
    mutationFn: () => splitApi.markPaid(share.shareId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['splits-owed-by-me'] }),
  });

  return (
    <Card className="gap-2">
      <ThemedText type="smallBold">{share.transactionDescription}</ThemedText>
      <ThemedText type="small" themeColor="textSecondary">
        Você deve pra {share.creatorName}
      </ThemedText>
      <View className="flex-row items-center justify-between">
        <ThemedText type="subtitle">{formatCents(share.amount)}</ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          {STATUS_LABELS[share.status] ?? share.status}
        </ThemedText>
      </View>
      {share.status === 'pending' && (
        <Button loading={markPaid.isPending} onPress={() => markPaid.mutate()}>
          Marcar como pago
        </Button>
      )}
    </Card>
  );
}

function OwedToMeCard({ share }: { share: OwedToMeShare }) {
  const queryClient = useQueryClient();
  const confirm = useMutation({
    mutationFn: () => splitApi.confirm(share.shareId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['splits-owed-to-me'] });
      queryClient.invalidateQueries({ queryKey: ['summary'] });
    },
  });

  return (
    <Card className="gap-2">
      <ThemedText type="smallBold">{share.transactionDescription}</ThemedText>
      <ThemedText type="small" themeColor="textSecondary">
        {share.participantName} te deve
      </ThemedText>
      <View className="flex-row items-center justify-between">
        <ThemedText type="subtitle">{formatCents(share.amount)}</ThemedText>
        <ThemedText type="small" themeColor="textSecondary">
          {STATUS_LABELS[share.status] ?? share.status}
        </ThemedText>
      </View>
      <Button loading={confirm.isPending} onPress={() => confirm.mutate()}>
        Confirmar recebimento
      </Button>
    </Card>
  );
}

export default function SplitsScreen() {
  const [tab, setTab] = useState<'owed-by-me' | 'owed-to-me'>('owed-by-me');

  const { data: owedByMe, isLoading: loadingOwedByMe } = useQuery({
    queryKey: ['splits-owed-by-me'],
    queryFn: splitApi.listOwedByMe,
  });
  const { data: owedToMe, isLoading: loadingOwedToMe } = useQuery({
    queryKey: ['splits-owed-to-me'],
    queryFn: splitApi.listOwedToMe,
  });

  return (
    <Screen className="gap-6 pb-28">
      <View className="flex-row items-center gap-3">
        <Pressable onPress={() => router.back()} hitSlop={8} className="active:opacity-60">
          <ArrowLeftIcon size={22} />
        </Pressable>
        <ThemedText type="subtitle">Splits pendentes</ThemedText>
      </View>

      <View className="flex-row gap-2">
        <Button variant={tab === 'owed-by-me' ? 'default' : 'outline'} size="sm" onPress={() => setTab('owed-by-me')}>
          O que eu devo
        </Button>
        <Button variant={tab === 'owed-to-me' ? 'default' : 'outline'} size="sm" onPress={() => setTab('owed-to-me')}>
          O que me devem
        </Button>
      </View>

      {tab === 'owed-by-me' ? (
        loadingOwedByMe ? (
          <ActivityIndicator />
        ) : owedByMe && owedByMe.length > 0 ? (
          <View className="gap-3">
            {owedByMe.map((share) => (
              <OwedByMeCard key={share.shareId} share={share} />
            ))}
          </View>
        ) : (
          <Card className="items-center py-8">
            <ThemedText type="small" themeColor="textSecondary">
              Você não deve nada no momento.
            </ThemedText>
          </Card>
        )
      ) : loadingOwedToMe ? (
        <ActivityIndicator />
      ) : owedToMe && owedToMe.length > 0 ? (
        <View className="gap-3">
          {owedToMe.map((share) => (
            <OwedToMeCard key={share.shareId} share={share} />
          ))}
        </View>
      ) : (
        <Card className="items-center py-8">
          <ThemedText type="small" themeColor="textSecondary">
            Ninguém te deve nada no momento.
          </ThemedText>
        </Card>
      )}
    </Screen>
  );
}

// apps/dashboard/src/routes/(app)/more/splits/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { formatCents } from '$lib/money';

	let { data } = $props();

	let tab = $state<'owed-by-me' | 'owed-to-me'>('owed-by-me');

	const STATUS_LABELS: Record<string, string> = {
		pending: 'Pendente',
		paid: 'Pago, aguardando confirmação',
		confirmed: 'Confirmado'
	};
</script>

<div class="flex flex-col gap-6">
	<h2 class="text-lg font-semibold">Splits</h2>

	<div class="flex gap-2">
		<Button
			variant={tab === 'owed-by-me' ? 'default' : 'outline'}
			size="sm"
			onclick={() => (tab = 'owed-by-me')}
		>
			O que eu devo
		</Button>
		<Button
			variant={tab === 'owed-to-me' ? 'default' : 'outline'}
			size="sm"
			onclick={() => (tab = 'owed-to-me')}
		>
			O que me devem
		</Button>
	</div>

	{#if tab === 'owed-by-me'}
		{#if data.owedByMe.length > 0}
			<div class="flex flex-col gap-2">
				{#each data.owedByMe as share (share.shareId)}
					<Card.Root>
						<Card.Content class="flex flex-col gap-2 py-4">
							<p class="text-sm font-medium">{share.transactionDescription}</p>
							<p class="text-sm text-muted-foreground">Você deve pra {share.creatorName}</p>
							<div class="flex items-center justify-between">
								<span class="text-lg font-semibold">{formatCents(share.amount)}</span>
								<span class="text-sm text-muted-foreground">{STATUS_LABELS[share.status]}</span>
							</div>
							{#if share.status === 'pending'}
								<form method="POST" action="?/markPaid" use:enhance>
									<input type="hidden" name="shareId" value={share.shareId} />
									<Button type="submit" class="w-full">Marcar como pago</Button>
								</form>
							{/if}
						</Card.Content>
					</Card.Root>
				{/each}
			</div>
		{:else}
			<Card.Root>
				<Card.Content class="py-6 text-center text-sm text-muted-foreground">
					Você não deve nada no momento.
				</Card.Content>
			</Card.Root>
		{/if}
	{:else if data.owedToMe.length > 0}
		<div class="flex flex-col gap-2">
			{#each data.owedToMe as share (share.shareId)}
				{@const canConfirm = share.status === (share.participantUserId ? 'paid' : 'pending')}
				<Card.Root>
					<Card.Content class="flex flex-col gap-2 py-4">
						<p class="text-sm font-medium">{share.transactionDescription}</p>
						<p class="text-sm text-muted-foreground">{share.participantName} te deve</p>
						<div class="flex items-center justify-between">
							<span class="text-lg font-semibold">{formatCents(share.amount)}</span>
							<span class="text-sm text-muted-foreground">{STATUS_LABELS[share.status]}</span>
						</div>
						{#if canConfirm}
							<form method="POST" action="?/confirm" use:enhance>
								<input type="hidden" name="shareId" value={share.shareId} />
								<Button type="submit" class="w-full">Confirmar recebimento</Button>
							</form>
						{:else}
							<p class="text-sm text-muted-foreground">
								Aguardando {share.participantName} marcar como pago.
							</p>
						{/if}
					</Card.Content>
				</Card.Root>
			{/each}
		</div>
	{:else}
		<Card.Root>
			<Card.Content class="py-6 text-center text-sm text-muted-foreground">
				Ninguém te deve nada no momento.
			</Card.Content>
		</Card.Root>
	{/if}
</div>
